### ISSUE TITLE
Create a React App

### ISSUE THREAD

**Issue by aftabrehan** [appwex/react-ui-components#1]
## Just a Quick guideline

- Clone the repo https://github.com/appwex/react-ui-components
- Create a React app in it
- Push the changes in a new branch
- Raise a PR
- Request @aftabrehan a review

**Comment by mrxshinji** [comment]
https://github.com/appwex/react-ui-components/pull/2
Created react app

**Comment by aftabrehan** [comment]
Fixed in #2
