### ISSUE TITLE
Sidebar Component

### ISSUE THREAD

**Issue by aftabrehan** [appwex/react-ui-components#22]
As per [Figma](https://www.figma.com/file/qOoG6pKbWKi2ldzHT2cHA6/Crypto-Component---Light-Mode-(Part-2)-(Community)?node-id=1%3A3016&t=F6TlmBnEH33CxrmT-0)

### Preview

<div align="center">

Light | Dark
-- | --
<img src="https://user-images.githubusercontent.com/93012310/205493759-bfef53f8-8937-4bfa-b571-550200f42e87.png" /> | <img src="https://user-images.githubusercontent.com/93012310/205493705-9f246831-3bea-4e90-bf82-33e018a30c77.png" />

</div>

##### Variants

- [x] Light
- [ ] Dark

**Comment by saroshfarhan** [comment]
Light mode completed.
working on dark mode colors
